### PR TITLE
feat(accounts): Add redirect handling to /accounts/social SignupView

### PR DESCRIPTION
**Pull request by denisemauldin**
# Submitting Pull Requests

## General

 - [ ] Make sure you use [semantic commit messages](https://seesparkbox.com/foundry/semantic_commit_messages).
       Examples: `"fix(google): Fixed foobar bug"`, `"feat(accounts): Added foobar feature"`.
 - [ ] All Python code must formatted using Black, and clean from pep8 and isort issues.
 - [ ] JavaScript code should adhere to [StandardJS](https://standardjs.com).
 - [ ] If your changes are significant, please update `ChangeLog.rst`.
 - [ ] If your change is substantial, feel free to add yourself to `AUTHORS`.

 ## Provider Specifics

 In case you add a new provider:

- [ ] Make sure unit tests are available.
- [ ] Add an entry of your provider in `test_settings.py::INSTALLED_APPS` and `docs/installation.rst::INSTALLED_APPS`.
- [ ] Add documentation to `docs/providers.rst`.
- [ ] Add an entry to the list of supported providers over at `docs/overview.rst`.

### CODE REVIEW

**Review by ranchodeluxe — CHANGES_REQUESTED** [review]
makes sense, looks good. One request:

Anthony and I have noticed that we don't actually update `__version__` on releases even if we are changing the sha in `Platform`. Can we bump this too please so there's no confusion about which version of our own we have installed?

`setup.py` references this: https://github.com/bevy/django-allauth/blob/master/allauth/__init__.py#L11

**Comment by denisemauldin** [comment]
Yeah, right now we've been not doing that so we can PR to upstream I believe.  We pin platform to a specific hash to indicate the code that should be installed.  What are your thoughts about how we could do this better?

**Comment by ranchodeluxe** [comment]
> Yeah, right now we've been not doing that so we can PR to upstream I believe. We pin platform to a specific hash to indicate the code that should be installed. What are your thoughts about how we could do this better?

I guess don't do anything then 😄 and I'll re-review

**Review by ranchodeluxe — APPROVED** [review]
just do it

**Review by jrfernandes — APPROVED** [review]
:+1: :shipit:

**Pull request merged**
